#!/bin/bash
#Description: Jenkins installation
#Author: Dora
sudo yum install java-1.8.0 -y

yum -y install wget
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
yum -y install jenkins

sudo yum install jenkins -y

sudo service jenkins start

systemctl start jenkins.service
